%YAML:1.0

BaseConfig:
  minDetectorConfidence: 0.6
  minTrackerConfidence: 0.5
  minMatchingScore4Overall: 0.3
  minTrailingScore4Overall: 0.4
  minHits4Visibility: 3
  probationAge: 3
  maxShadowTrailingAge: 30
  earlyTerminationAge: 1

TargetManagement:
  enableBboxUnClipping: 1
  maxTargetsPerStream: 30
  preserveStreamUpdateOrder: 0
  minIouDiff4NewTarget: 0.7
  minTrackerConfidence: 0.5
  maxShadowTrailingAge: 60
  probationAge: 5
  earlyTerminationAge: 1

TrajectoryManagement:
  useUniqueID: 1

DataAssociator:
  dataAssociatorType: 0
  associationMatcherType: 1
  checkClassMatch: 1
  minMatchingScore4Overall: 0.3
  minMatchingScore4SizeSimilarity: 0.5
  minMatchingScore4Appearance: 0.3
  matchingScoreWeight4SizeSimilarity: 60.0
  matchingScoreWeight4Appearance: 40.0

StateEstimator:
  stateEstimatorType: 2
  noiseWeightVar4Loc: 0.05
  noiseWeightVar4Vel: 0.00625
  useAspectRatio: 1
